export const tagTypes = {
  auth: "Auth",
  jobBoard: "JobBoard",
  user: "User",
  passenger: "Passenger",
  profile: "Profile",
  setting: "Setting",
  conversation: "Conversation",
  payment: "Payment",
  feedback: "Feedback",
  promo: "Promo",
  report: "Report",
  overview: "Overview",
  fare: "Fare",
  ride: "Ride",
  driver: "Driver",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.jobBoard,
  tagTypes.user,
  tagTypes.passenger,
  tagTypes.profile,
  tagTypes.setting,
  tagTypes.conversation,
  tagTypes.payment,
  tagTypes.feedback,
  tagTypes.promo,
  tagTypes.report,
  tagTypes.overview,
  tagTypes.fare,
  tagTypes.ride,
  tagTypes.driver,
];
